---
# RBAC Configuration
rbac:
  # Specify an existing ClusterRole if you do not want to create a new one
  existingClusterRole: null

  # Names for the ClusterRole and ClusterRoleBinding
  clusterRole:
    name: null

  clusterRoleBinding:
    name: null

  # ServiceAccount configuration
  serviceAccount:
    name: null
    namespace: null

# Deployment Configuration
deployment:
  # nuopMode: manager | standard | managed
  replicas: 1
  # Operator image configuration
  image:
    repository: ghcr.io/ck3mp3r/nuop
    tag: latest
    pullPolicy: IfNotPresent

  # Logging configuration
  log:
    level: info
    format: plain
  # labels:
  #   environment: production
  #   team: devops
