---
name: nuop
env:
  KUBECONFIG: ./kind/kube.config

windows:
  - name: code
    panes:
      - name: Editor
        commands:
          - command: ^$env.EDITOR

  - name: misc
    flex_direction: row
    panes:
      - flex: 1
      - flex: 1

  - name: k9s
    panes:
      - script: |
          #!/usr/bin/env nu

          if (kind get clusters | find "nuop" | is-empty) {
            kind create cluster --name nuop --config ./kind/kind-cluster.yaml
            kind get kubeconfig -n nuop
            | from yaml
            | reject clusters.0.cluster.certificate-authority-data
            | upsert clusters.0.cluster.insecure-skip-tls-verify true
            | upsert clusters.0.cluster.server https://127.0.0.1:7543
            | to yaml
            | save -f ./kind/kube.config
            kubectx kind-nuop
          }
          k9s
