default_install_hook_types = ["pre-commit"]

[[repos]]
repo = "builtin"
hooks = [
  { id = "end-of-file-fixer" },
  { id = "trailing-whitespace" },
]

[[repos]]
repo = "local"

[[repos.hooks]]
id = "nix-fmt"
name = "nix fmt"
language = "system"
entry = "nix fmt ."
pass_filenames = false
stages = ["pre-commit"]

[[repos.hooks]]
id = "cargo-fmt"
name = "cargo fmt"
language = "system"
entry = "cargo fmt --all --manifest-path operator/Cargo.toml"
pass_filenames = false
stages = ["pre-commit"]

[[repos.hooks]]
id = "check-merge-conflicts"
name = "check merge conflicts"
language = "system"
entry = "git diff --check --cached"
pass_filenames = false
stages = ["pre-commit"]
