---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-alpha
  namespace: default
  labels:
    app: foo-bar
    app.kubernetes.io/replicate: "yes"
  annotations:
    app.kubernetes.io/target-namespaces: "foo,bar,baz"
    # app.kubernetes.io/target-method: "exclude" # defaults to include

data:
  key1: value1
  key2: value2
  key3: value3
