---
# Local Development Example
# Shows volume-mounted local scripts for development workflow

apiVersion: kemper.buzz/v1alpha1
kind: NuOperator
metadata:
  name: local-dev
  namespace: default
spec:
  serviceAccountName: local-dev-sa
  env:
    - name: RUST_LOG
      value: debug
    - name: DEV_MODE
      value: "true"
  mappings:
    - name: my-local-script
      group: ""
      version: v1
      kind: ConfigMap
      labelSelectors:
        environment: development
  sources:
    # Local volume mount (for development)
    - location: /opt/dev-scripts
      path: /scripts

---
# ServiceAccount for local development
apiVersion: v1
kind: ServiceAccount
metadata:
  name: local-dev-sa
  namespace: default

---
# Deployment with volume mount for local development
apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-dev-operator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: local-dev-operator
  template:
    metadata:
      labels:
        app: local-dev-operator
    spec:
      serviceAccountName: local-dev-sa
      containers:
        - name: operator
          image: ghcr.io/ck3mp3r/nuop:latest
          env:
            - name: NUOP_MODE
              value: managed
            - name: RUST_LOG
              value: debug
          volumeMounts:
            - name: dev-scripts
              mountPath: /opt/dev-scripts
      volumes:
        - name: dev-scripts
          hostPath:
            path: /path/to/your/local/scripts
            type: Directory
