---
apiVersion: kemper.buzz/v1alpha1
kind: NuOperator
metadata:
  name: basic-example
  namespace: default
spec:
  serviceAccountName: basic-operator-sa
  env:
    - name: RUST_LOG
      value: info
    - name: ENVIRONMENT
      value: production
  mappings:
    - name: pod-watcher
      version: v1
      kind: Pod
  sources:
    - location: https://github.com/example/scripts.git
      path: /scripts
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: basic-operator-sa
  namespace: default
