apiVersion: kemper.buzz/v1alpha1
kind: NuOperator
metadata:
  name: foo-bar
  namespace: default
spec:
  serviceAccountName: nushell-operator-nuop-sa
  env:
    - name: RUST_LOG
      value: debug
  mappings:
    - name: secret-cloner
      version: v1
      kind: Secret
      labelSelectors:
        app: foo-bar
  sources:
    - location: https://github.com/ck3mp3r/nuop.git?dir=operator/scripts&ref=operators
      path: foo
      # credentials:
      #   username:
      #     name: git-creds-foo-bar
      #     key: username
      #   password:
      #     name: git-creds-foo-bar
      #     key: password
      # token:
      #   name: git-creds-secret-cloner
      #   key: token
      #
---
apiVersion: kemper.buzz/v1alpha1
kind: NuOperator
metadata:
  name: foo-baz
  namespace: default
spec:
  serviceAccountName: nushell-operator-nuop-sa
  env:
    - name: RUST_LOG
      value: debug
  mappings:
    - name: config-replicator
      version: v1
      kind: ConfigMap
      labelSelectors:
        app: foo-baz
  sources:
    - location: https://github.com/ck3mp3r/k8s-playground.git?dir=operator/scripts&ref=operators
      path: foo
      # credentials:
      #   username:
      #     name: git-creds-foo-bar
      #     key: username
      #   password:
      #     name: git-creds-foo-bar
      #     key: password
      # token:
      #   name: git-creds-secret-cloner
      #   key: token
      #
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nushell-operator-nuop-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: foo-bar-operator-nuop-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nushell-operator-nuop-clusterrole
subjects:
  - kind: ServiceAccount
    name: nushell-operator-nuop-sa
    namespace: default
