---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  namespace: production
  labels:
    app: webapp
    monitor: enabled
    health-check: required
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: nginx:1.21
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: production
  labels:
    app: webapp
    health-check: required
spec:
  selector:
    app: webapp
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
  namespace: dev
  labels:
    environment: development
    owner: developer
    app: debug-tools
spec:
  containers:
    - name: debug
      image: busybox:1.35
      command: ["sleep", "3600"]
---
apiVersion: v1
kind: Namespace
metadata:
  name: auto-namespace
  labels:
    auto-provision: "true"
    team: platform
