---
apiVersion: v1
kind: Secret
metadata:
  name: git-creds-beta
  namespace: default
  labels:
    app: foo-bar
    app.kubernetes.io/replicate: "yes"
  annotations:
    app.kubernetes.io/target-namespaces: "foo,bar,baz"
    # app.kubernetes.io/target-method: "exclude" # defaults to include
type: Opaque
stringData:
  token: ghp_XXXXXXXXXXXXXXXXXXXX
