apiVersion: v1
kind: Secret
metadata:
  name: secret-beta
  namespace: default
  labels:
    app: foo-bar
    environment: staging
type: Opaque
stringData:
  api_key: sk-test-1234567890abcdef
  database_password: super-secret-password
  jwt_secret: jwt-signing-key-xyz
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-gamma
  namespace: production
  labels:
    app.kubernetes.io/replicate: "yes"
    environment: production
type: Opaque
stringData:
  oauth_client_secret: oauth-prod-secret-123
  encryption_key: aes-256-encryption-key
---
apiVersion: v1
kind: Secret
metadata:
  name: git-credentials-example
  namespace: default
  labels:
    type: git-auth
type: Opaque
stringData:
  username: automation-bot
  password: ghp_ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ
