[package]
name = "operator"
description = "Nushell Operator"
version = "0.2.0"
edition = "2024"

[profile.release]
opt-level = "z" # Optimize for size
lto = true # Enable Link Time Optimization
codegen-units = 1 # Reduce the number of codegen units to improve optimization
debug = false # Disable debug information
panic = "abort" # Abort on panic to reduce binary size
strip = "symbols" # Strip symbols to reduce binary size

[lib]
name = "operator"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.104"
async-trait = "0.1.92"
futures = "0.3.34"
k8s-openapi = { version = "0.28.0", features = ["latest","schemars" ] }
kube = { version = "4.2.0", features = ["runtime", "derive"] }
schemars = "1.2.2"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
serde_yaml = "0.9.34"
sha2 = "0.11.0"
tokio = { version = "1.53.1", features = ["full"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["fmt", "json"] }

[dev-dependencies]
mockall = "0.15.0"
http = "1.5.0"
tower-test = "0.4.0"
tempfile = "3.27.0"
bytes = "1.12.1"
chrono = { version = "0.4.45", features = ["serde"] }

[[bin]]
name = "generate"
path = "src/nuop/manager/model/generate.rs"
