---
name: Test

on:
  workflow_dispatch:
  push:
    paths:
      - flake.*
      - devshell.toml
      - operator/Cargo.*
      - operator/flake.*
      - operator/src/**
      - .github/workflows/**
  pull_request:
    paths:
      - flake.*
      - devshell.toml
      - operator/Cargo.*
      - operator/flake.*
      - operator/src/**
      - .github/workflows/**

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Detect Nix system
        id: detect_system
        if: ${{ env.ACT }}
        run: |
          if [[ "${{ runner.os }}" == "Linux" && "${{ runner.arch }}" == "X64" ]]; then
            echo "nix_system=x86_64-linux" >> $GITHUB_OUTPUT
          elif [[ "${{ runner.os }}" == "Linux" && "${{ runner.arch }}" == "ARM64" ]]; then
            echo "nix_system=aarch64-linux" >> $GITHUB_OUTPUT
          fi

      - name: Download Nix installer
        if: ${{ env.ACT }}
        run: |
          curl -L https://cf.install.determinate.systems/nix-installer/stable/${{ steps.detect_system.outputs.nix_system }}  -o /tmp/nix-installer-${{ steps.detect_system.outputs.nix_system }}
          chmod +x /tmp/nix-installer-${{ steps.detect_system.outputs.nix_system }}

      - uses: DeterminateSystems/nix-installer-action@main
        if: ${{ !env.ACT }}

      - uses: DeterminateSystems/nix-installer-action@main
        if: ${{ env.ACT }}
        with:
          local-root: /tmp

      - uses: DeterminateSystems/flake-checker-action@main

      - run: |
          nix profile install nixpkgs#nushell
          sudo ln -s $(which nu) /usr/bin/nu

      - name: run tests
        run: |
          nix develop --command cargo test --manifest-path operator/Cargo.toml
