---
name: Test

on:
  workflow_dispatch:
  pull_request:
    paths:
      - flake.*
      - devshell.toml
      - operator/Cargo.*
      - operator/flake.*
      - operator/src/**
      - .github/workflows/**

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/flake-checker-action@main

      - run: |
          nix profile install nixpkgs#nushell
          nix develop --command op-tests
