---
name: Test

on:
  workflow_dispatch:
  push:
    paths:
      - flake.*
      - devenv.nix
      - operator/Cargo.*
      - operator/flake.*
      - operator/src/**
      - .github/workflows/**

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Detect Nix system
        id: detect_system
        if: ${{ env.ACT }}
        run: |
          if [[ "${{ runner.os }}" == "Linux" && "${{ runner.arch }}" == "X64" ]]; then
            echo "nix_system=x86_64-linux" >> $GITHUB_OUTPUT
          elif [[ "${{ runner.os }}" == "Linux" && "${{ runner.arch }}" == "ARM64" ]]; then
            echo "nix_system=aarch64-linux" >> $GITHUB_OUTPUT
          fi

      - name: Download Nix installer
        if: ${{ env.ACT }}
        run: |
          curl -L https://cf.install.determinate.systems/nix-installer/stable/${{ steps.detect_system.outputs.nix_system }}  -o /tmp/nix-installer-${{ steps.detect_system.outputs.nix_system }}
          chmod +x /tmp/nix-installer-${{ steps.detect_system.outputs.nix_system }}

      - uses: DeterminateSystems/nix-installer-action@main
        if: ${{ !env.ACT }}
        with:
          flakehub: false

      - uses: DeterminateSystems/nix-installer-action@main
        if: ${{ env.ACT }}
        with:
          local-root: /tmp
          flakehub: false

      - uses: DeterminateSystems/flake-checker-action@main

      - uses: DeterminateSystems/magic-nix-cache-action@main
        with:
          use-flakehub: false

      - name: run tests
        run: |
          nix develop .#ci --no-pure-eval --command cargo test --manifest-path operator/Cargo.toml -- --include-ignored
