---
name: Test

on:
  workflow_dispatch:
  push:
    paths:
      - flake.*
      - devshell.toml
      - operator/Cargo.*
      - operator/flake.*
      - operator/src/**
      - .github/workflows/**
  pull_request:
    paths:
      - flake.*
      - devshell.toml
      - operator/Cargo.*
      - operator/flake.*
      - operator/src/**
      - .github/workflows/**

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      - run: |
          nix profile install nixpkgs#nushell
          sudo ln -s $(which nu) /usr/bin/nu

      - name: run tests
        run: |
          nix develop --command cargo test --manifest-path operator/Cargo.toml
